name: widgets_library
description: Circle loader widget
version: 0.1.0
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
